### ISSUE TITLE
Texture issue

### ISSUE THREAD

**Issue by 00benallen** [jaxxa/ED-Embrasures#1]
Playing on alpha 13 with a few mods, not many, and the embrasure texture seems to be missing. It works, but shows up as a purple rectangle.
![screen shot 2016-05-15 at 12 11 34 am](https://cloud.githubusercontent.com/assets/6377690/15271975/bc8916e8-1a31-11e6-821a-e7e12fbd9a61.png)
![screen shot 2016-05-15 at 12 12 26 am](https://cloud.githubusercontent.com/assets/6377690/15271976/c2117100-1a31-11e6-8eb9-7cc1b06a2b8b.png)

**Comment by jaxxa** [comment]
ED-Embrasures-CR is a compatibility patch that requires that ED-Embrasures is installed and loaded before it in the load order.

If that does not fix your issue feel free to reopen it.

**Comment by 00benallen** [comment]
thank you I was being a dummy!
